name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f environment.yml ]; then
          conda env update -f environment.yml
        fi
        pip install pytest pytest-cov
        
    - name: Test with pytest
      run: |
        pytest --cov=core tests/
        
    - name: Upload coverage report
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: false
